// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URL_Shortener.DatabaseContexts;

namespace URL_Shortener.Migrations
{
    [DbContext(typeof(URLContext))]
    [Migration("20200910210637_LinkTableBuild")]
    partial class LinkTableBuild
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("URL_Shortener.Models.URL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BaseURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalIP")
                        .HasColumnType("text");

                    b.Property<string>("ShortenedIdentifier")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UrlSet");
                });

            modelBuilder.Entity("URL_Shortener.Models.UrlUsers", b =>
                {
                    b.Property<int>("UrlId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UrlId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UrlUsersSet");
                });

            modelBuilder.Entity("URL_Shortener.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateInitialised")
                        .HasColumnType("datetime");

                    b.Property<bool>("HasAdminPrivileges")
                        .HasColumnType("bit");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUsedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UseCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserSet");
                });

            modelBuilder.Entity("URL_Shortener.Models.UrlUsers", b =>
                {
                    b.HasOne("URL_Shortener.Models.URL", "Url")
                        .WithMany("UrlUsers")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("URL_Shortener.Models.User", "User")
                        .WithMany("urlUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
